module.exports = {
  app: {
    title: '电子科技大学 NetUnion 协会',
  },
  newsList: {
    newsItems: [
      {
        tweetId: '4',
        tweetTitle: '这是一条新闻公告',
        tweetAuthor: 'tweetAuthor',
        tweetType: 'news',
        tweetAccent: 'success',
        tweetDate: '2020-10-03',
        tweetContent: '这是一条简单的新闻公告，以及这是所有内容。',
        tweetLocation: '',
        tweetLink: '',
      },
      {
        tweetId: '3',
        tweetTitle: '我们把所有镜像都鲨了',
        tweetAuthor: 'admin',
        tweetType: 'news',
        tweetAccent: 'danger',
        tweetDate: '2020-10-02',
        tweetContent: '为缓解镜像站目前紧迫的存储空间问题，我们决定暂时停止所有镜像服务并将相关请求重定向至他处。',
        tweetLocation: '',
        tweetLink: '',
      },
      {
        tweetId: '2',
        tweetTitle: '我们把 Fedora 镜像鲨了',
        tweetAuthor: 'admin',
        tweetType: 'news',
        tweetAccent: 'info',
        tweetDate: '2020-10-01',
        tweetContent: '为缓解镜像站目前紧迫的存储空间问题，我们决定暂时停止此镜像服务并将相关请求重定向至他处。',
        tweetLocation: '',
        tweetLink: '',
      },
      {
        tweetId: '1',
        tweetTitle: '这是第一条新闻公告',
        tweetAuthor: 'none',
        tweetType: 'news',
        tweetAccent: '',
        tweetDate: '2020-09-01',
        tweetContent: '这是第一条简单的新闻公告，以及这是所有内容。',
        tweetLocation: '',
        tweetLink: '',
      },
    ],
  },
};
